defmodule SimpleTodo do
  def new(), do: MultiDict.new()

  # The two arguments are:
  # a to-do list instance, generated by the previous new()
  # a Map describing the entry
  #
  # Example:
  # simple_map = %{date: ~D[2023-12-19], title: "Play"}
  # SimpleTodo.add_entry(%{}, simple_map)

  def add_entry(todo_list, entry) do
    MultiDict.add(todo_list, entry.date, entry)
  end

  def entries(todo_list, date) do
    MultiDict.get(todo_list, date)
  end
end
